[package]
name = "ensos"
version = "0.1.0"
authors = ["Shotaro Yamada <sinkuu@sinkuu.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"